import type { Database } from 'bun:sqlite';
import { createHash, randomUUID } from 'node:crypto';
import { closeSync, fsyncSync, lstatSync, openSync, readFileSync, realpathSync, renameSync, unlinkSync, writeFileSync } from 'node:fs';
import { isAbsolute, relative, resolve } from 'node:path';

export const RECORDS_PATH='.memory/RECORDS.md';
export type ProjectionStatus={state:'empty'|'synced'|'pending'|'conflict'; path:string; error?:string};
const hash=(s:string)=>createHash('sha256').update(s).digest('hex');
const quote=(s:string)=>s.split('\n').map(line=>'> '+line).join('\n');
type Row={body:string; last_hash:string|null};

// Called inside the same SQLite transaction as versions/checkpoint. The desired
// document is a durable outbox, not a second independently authored truth source.
export function stageProjection(db:Database) {
  const rows=db.query(`SELECT v.data,v.version,v.time FROM versions v JOIN
    (SELECT id,MAX(version) version FROM versions GROUP BY id) n ON v.id=n.id AND v.version=n.version ORDER BY v.id`).all() as any[];
  if(!rows.length) return;
  const parts=['# Memory registry\n\nGenerated by huimem; do not edit this file. Update records through project_memory.\n'+
    'This is a readable snapshot, not independent evidence. Check source freshness before use.\n'+
    'Keep human notes in MEMORY.md and ADRs. Acceptance does not verify added interpretations.\n'];
  for(const row of rows) {
    const c=JSON.parse(row.data);
    parts.push(`## ${c.id}\n\nKind: ${c.kind} · Status: ${c.status} · Version: ${row.version} · Saved: ${row.time}\n\n`+
      `Interpretation (unverified beyond source evidence):\n${quote(c.text)}\n\n`+
      `Source quote:\n${quote(c.source.quote)}\n\n`+
      (c.rationale ? `Recorded rationale (verify against source):\n${quote(c.rationale)}\n\n` : '')+
      `Source: ${JSON.stringify(c.source.path ? {path:c.source.path,hash:c.source.hash} : {episode:c.source.episode})}\n`+
      (c.links?.length ? `Related records: ${c.links.join(', ')}\n` : ''));
  }
  db.query('INSERT INTO projection(id,body,last_hash) VALUES(1,?,NULL) ON CONFLICT(id) DO UPDATE SET body=excluded.body').run(parts.join('\n'));
}

function filePath(root:string) {
  const base=realpathSync(root), parent=realpathSync(resolve(root,'.memory'));
  const rel=relative(base,parent);
  if(rel.startsWith('..') || isAbsolute(rel)) throw new Error('PATH: memory directory outside project');
  return resolve(parent,'RECORDS.md');
}
function readHash(path:string) {
  try {
    if(!lstatSync(path).isFile()) throw new Error('PROJECTION_PATH: expected a regular file, not a directory or symlink');
    return hash(readFileSync(path,'utf8'));
  } catch(e:any) { if(e.code==='ENOENT') return null; throw e; }
}
function status(row:Row|null,root:string):ProjectionStatus {
  if(!row) return {state:'empty',path:RECORDS_PATH};
  try {
    const current=readHash(filePath(root));
    if(current===hash(row.body)) return {state:'synced',path:RECORDS_PATH};
    if(current!==null && current!==row.last_hash)
      return {state:'conflict',path:RECORDS_PATH,error:'RECORDS.md was edited outside huimem. Preserve it elsewhere, then run /huimem sync. Nothing will be overwritten.'};
    return {state:'pending',path:RECORDS_PATH};
  } catch(e) { return {state:'pending',path:RECORDS_PATH,error:String(e)}; }
}
export function projectionStatus(db:Database,root:string) {
  return status(db.query('SELECT body,last_hash FROM projection WHERE id=1').get() as Row|null,root);
}
export function syncProjection(db:Database,root:string):ProjectionStatus {
  try {
    // Serialize cooperating OMP processes through the SQLite writer lock.
    return db.transaction(()=>{
      const row=db.query('SELECT body,last_hash FROM projection WHERE id=1').get() as Row|null;
      const st=status(row,root);
      if(!row || st.state==='conflict' || st.error) return st;
      if(st.state==='synced') {
        db.query('UPDATE projection SET last_hash=? WHERE id=1').run(hash(row.body));
        return st; // Also recovers a rename completed just before a process exit.
      }
      const path=filePath(root), before=readHash(path);
      const temp=resolve(realpathSync(resolve(root,'.memory')),`.records-${randomUUID()}.tmp`);
      let fd:number|undefined;
      try {
        fd=openSync(temp,'wx'); writeFileSync(fd,row.body,'utf8'); fsyncSync(fd); closeSync(fd); fd=undefined;
        if(readHash(path)!==before) throw new Error('PROJECTION_CONFLICT: file changed during publication; retry sync after review');
        renameSync(temp,path);
        db.query('UPDATE projection SET last_hash=? WHERE id=1').run(hash(row.body));
        return {state:'synced',path:RECORDS_PATH} as ProjectionStatus;
      } finally {
        if(fd!==undefined) closeSync(fd);
        try { unlinkSync(temp); } catch(e:any) { if(e.code!=='ENOENT') throw e; }
      }
    }).immediate();
  } catch(e) { return {state:'pending',path:RECORDS_PATH,error:String(e)}; }
}
